(venv) PS D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:00:22
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:08:23
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /__umi_ping
[15/Aug/2025 20:09:39] "GET /__umi_ping HTTP/1.1" 404 2728
Not Found: /signup
[15/Aug/2025 20:09:39] "GET /signup HTTP/1.1" 404 2716
Not Found: /.well-known/appspecific/com.chrome.devtools.json
Not Found: /favicon.ico
[15/Aug/2025 20:09:39] "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2842
[15/Aug/2025 20:09:39] "GET /favicon.ico HTTP/1.1" 404 2731
[15/Aug/2025 20:10:01] "GET /signup HTTP/1.1" 404 2716
Not Found: /.well-known/appspecific/com.chrome.devtools.json
[15/Aug/2025 20:10:01] "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2842
D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\serializers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:12:43
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
(venv) PS D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:19:10
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /__umi_ping
[15/Aug/2025 20:23:16] "GET /__umi_ping HTTP/1.1" 404 2728
Not Found: /signup
[15/Aug/2025 20:23:16] "GET /signup HTTP/1.1" 404 2716
Not Found: /.well-known/appspecific/com.chrome.devtools.json
[15/Aug/2025 20:23:16] "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2842
[15/Aug/2025 20:26:08] "POST /api/website/v1/accounts/user/create/ HTTP/1.1" 201 74
Internal Server Error: /api/website/v1/accounts/profile/create/
Traceback (most recent call last):
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\views.py", line 85, in post
    data = serializer.save()
           ^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\serializers.py", line 80, in create
    profile = super().create(validated_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\cacheops\transaction.py", line 98, in execute
    result = self._no_monkey.execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
[15/Aug/2025 20:26:17] "POST /api/website/v1/accounts/profile/create/ HTTP/1.1" 500 222275
D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\serializers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:27:40
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
(venv) PS D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:29:13
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /signup
[15/Aug/2025 20:29:19] "GET /signup HTTP/1.1" 404 2716
Not Found: /.well-known/appspecific/com.chrome.devtools.json
[15/Aug/2025 20:29:19] "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2842
[15/Aug/2025 20:29:52] "POST /api/website/v1/accounts/user/create/ HTTP/1.1" 201 79
Internal Server Error: /api/website/v1/accounts/profile/create/
Traceback (most recent call last):
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\views.py", line 85, in post
    data = serializer.save()
           ^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\serializers.py", line 80, in create
    profile = super().create(validated_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\cacheops\transaction.py", line 98, in execute
    result = self._no_monkey.execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\sqlite    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
[15/Aug/2025 20:29:57] "POST /api/website/v1/accounts/profile/create/ HTTP/1.1" 500 222310
(venv) PS D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:39:30
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
(venv) PS D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 20:58:05
Django version 3.2.19, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /__umi_ping
[15/Aug/2025 20:58:24] "GET /__umi_ping HTTP/1.1" 404 2728
Not Found: /signup
[15/Aug/2025 20:58:24] "GET /signup HTTP/1.1" 404 2716
Not Found: /favicon.ico
[15/Aug/2025 20:58:24] "GET /favicon.ico HTTP/1.1" 404 2731
Not Found: /.well-known/appspecific/com.chrome.devtools.json
[15/Aug/2025 20:58:24] "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2842
[15/Aug/2025 20:59:19] "POST /api/website/v1/accounts/user/create/ HTTP/1.1" 201 81
ProfileCreationSerializer: validated_data {'first_name': 'rgeg', 'last_name': 'wteragaw3', 'gender': 0, 'user_id': 3}
ProfileCreationSerializer: creating profile for user User obj: 3-rgeawgFWE343@t.com-rgeawgFWE343@t.com
Internal Server Error: /api/website/v1/accounts/profile/create/
Traceback (most recent call last):
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\views.py", line 85, in post
    data = serializer.save()
           ^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\core\website\api\v1\accounts\serializers.py", line 82, in create
    profile = super().create(validated_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\cacheops\transaction.py", line 98, in execute
    result = self._no_monkey.execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\G\jajoul.me\Coding with jajoul\Ponisha Projects\we2\backup\new we 2\wetoo\wetoo\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
[15/Aug/2025 20:59:22] "POST /api/website/v1/accounts/profile/create/ HTTP/1.1" 500 222752